<?xml version="1.0"?>
<!-- SPDX-FileCopyrightText: Copyright (c) 2025 SEW-EURODRIVE, Author: Leon Rafael Schönfeld -->
<!-- SPDX-License-Identifier: MIT -->
<package format="2">
  <name>urdf_viewer</name>
  <version>0.0.0</version>
  <description>The urdf_viewer package</description>

  <maintainer email="SEW-Dataset@sew-eurodrive.de"><yannick/maintainer>


  <license>MIT</license>






  <buildtool_depend>catkin</buildtool_depend>


  <export>
  </export>
</package>
